name: my first workflow for a java project
on:
  push:
    branches: [ ci-pipeline ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#          settings-path: ".m2/"
      - name: Build with Maven
          run: mvn --batch-mode --update-snapshots verify
#
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
#      - name: Publish package
#        run: mvn $MAVEN_CLI_OPTS clean deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#      - name: Copying target jar
#        run: |
#          mkdir myTarget
#          cp target/*.jar myTarget
#      - name: Uploading jar
#        uses: actions/upload-artifact@v2
#        with:
#          name: myPackage
#          path: myTarget
